# Generated by Django 5.2.6 on 2025-10-09 14:04

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_dhcp.fields.choice_array
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dcim", "0215_rackreservation_status"),
        ("extras", "0133_make_cf_minmax_decimal"),
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("next_server", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "server_hostname",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "boot_file_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offer_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                ("test", models.CharField(blank=True, max_length=255)),
                ("template_test", models.CharField(blank=True, max_length=255)),
                ("only_if_required", models.BooleanField(blank=True, null=True)),
                ("only_in_additional_list", models.BooleanField(blank=True, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Class",
                "verbose_name_plural": "Client Classes",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DDNS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic DNS Server",
                "verbose_name_plural": "Dynamic DNS Servers",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DHCPCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(blank=True, default="active", max_length=50),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Cluster",
                "verbose_name_plural": "DHCP Clusters",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HostReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("next_server", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "server_hostname",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "boot_file_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("duid", models.CharField(blank=True, max_length=255, null=True)),
                ("flex_id", models.CharField(blank=True, max_length=255, null=True)),
                ("circuit_id", models.CharField(blank=True, max_length=255, null=True)),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "assign_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assign_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "excluded_ipv6_prefixes",
                    models.ManyToManyField(
                        related_name="netbox_dhcp_excluded_ipv6_host_reservations",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "hw_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_dhcp_host_reservations",
                        to="dcim.macaddress",
                    ),
                ),
                (
                    "ipv4_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_dhcp_ipv4_host_reservations",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "ipv6_addresses",
                    models.ManyToManyField(
                        related_name="netbox_dhcp_ipv6_host_reservations",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "ipv6_prefixes",
                    models.ManyToManyField(
                        related_name="netbox_dhcp_ipv6_host_reservations",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Host Reservation",
                "verbose_name_plural": "Host Reservations",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OptionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("family", models.PositiveIntegerField(default=4)),
                ("space", models.CharField(default="dhcp4")),
                (
                    "code",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                ("type", models.CharField()),
                (
                    "record_types",
                    netbox_dhcp.fields.choice_array.ChoiceArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                ("encapsulate", models.CharField(blank=True, null=True)),
                ("array", models.BooleanField(blank=True, null=True)),
                ("standard", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Definition",
                "verbose_name_plural": "Option Definitions",
                "ordering": ("space", "code", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("assigned_object_id", models.PositiveBigIntegerField()),
                ("data", models.CharField(blank=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("csv_format", models.BooleanField(blank=True, null=True)),
                ("always_send", models.BooleanField(blank=True, null=True)),
                ("never_send", models.BooleanField(blank=True, null=True)),
                (
                    "assign_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assign_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="options",
                        to="netbox_dhcp.optiondefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": (
                    "definition__space",
                    "definition__code",
                    "definition__name",
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PDPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("pool_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "delegated_length",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(128),
                        ]
                    ),
                ),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "client_class_definitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="definition_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evaluate_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "excluded_prefix",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_dhcp_pd_excluded_pools",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_dhcp_pd_pools",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "require_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="require_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prefix Delegation Pool",
                "verbose_name_plural": "Prefix Delegation Pools",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("ddns_send_updates", models.BooleanField(blank=True, null=True)),
                ("ddns_override_no_update", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_override_client_update",
                    models.BooleanField(blank=True, null=True),
                ),
                ("ddns_replace_client_name", models.CharField(blank=True, null=True)),
                ("ddns_generated_prefix", models.CharField(blank=True, null=True)),
                ("ddns_qualifying_suffix", models.CharField(blank=True, null=True)),
                ("ddns_update_on_renew", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_conflict_resolution_mode",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "ddns_ttl_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ddns_ttl", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_min", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_max", models.PositiveIntegerField(blank=True, null=True)),
                ("hostname_char_set", models.CharField(blank=True, max_length=255)),
                (
                    "hostname_char_replacement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("pool_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "client_class_definitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="definition_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evaluate_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "ip_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_dhcp_pools",
                        to="ipam.iprange",
                    ),
                ),
                (
                    "require_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="require_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pool",
                "verbose_name_plural": "Pools",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("next_server", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "server_hostname",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "boot_file_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offer_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_send_updates", models.BooleanField(blank=True, null=True)),
                ("ddns_override_no_update", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_override_client_update",
                    models.BooleanField(blank=True, null=True),
                ),
                ("ddns_replace_client_name", models.CharField(blank=True, null=True)),
                ("ddns_generated_prefix", models.CharField(blank=True, null=True)),
                ("ddns_qualifying_suffix", models.CharField(blank=True, null=True)),
                ("ddns_update_on_renew", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_conflict_resolution_mode",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "ddns_ttl_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ddns_ttl", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_min", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_max", models.PositiveIntegerField(blank=True, null=True)),
                ("hostname_char_set", models.CharField(blank=True, max_length=255)),
                (
                    "hostname_char_replacement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("renew_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("rebind_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("match_client_id", models.BooleanField(blank=True, null=True)),
                ("authoritative", models.BooleanField(blank=True, null=True)),
                ("reservations_global", models.BooleanField(blank=True, null=True)),
                (
                    "reservations_out_of_pool",
                    models.BooleanField(blank=True, null=True),
                ),
                ("reservations_in_subnet", models.BooleanField(blank=True, null=True)),
                ("calculate_tee_times", models.BooleanField(blank=True, null=True)),
                (
                    "t1_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "t2_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "cache_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("cache_max_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "adaptive_lease_time_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("store_extended_info", models.BooleanField(blank=True, null=True)),
                ("allocator", models.CharField(blank=True, null=True)),
                ("pd_allocator", models.CharField(blank=True, null=True)),
                ("relay", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "interface_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rapid_commit", models.BooleanField(blank=True, null=True)),
                ("subnet_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "child_host_reservations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.hostreservation",
                    ),
                ),
                (
                    "child_pd_pools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.pdpool",
                    ),
                ),
                (
                    "child_pools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.pool",
                    ),
                ),
                (
                    "child_subnets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.subnet",
                    ),
                ),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "client_class_definitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="definition_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evaluate_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_dhcp_subnets",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "require_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="require_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet",
                "verbose_name_plural": "Subnets",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SharedNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("next_server", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "server_hostname",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "boot_file_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offer_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_send_updates", models.BooleanField(blank=True, null=True)),
                ("ddns_override_no_update", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_override_client_update",
                    models.BooleanField(blank=True, null=True),
                ),
                ("ddns_replace_client_name", models.CharField(blank=True, null=True)),
                ("ddns_generated_prefix", models.CharField(blank=True, null=True)),
                ("ddns_qualifying_suffix", models.CharField(blank=True, null=True)),
                ("ddns_update_on_renew", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_conflict_resolution_mode",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "ddns_ttl_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ddns_ttl", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_min", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_max", models.PositiveIntegerField(blank=True, null=True)),
                ("hostname_char_set", models.CharField(blank=True, max_length=255)),
                (
                    "hostname_char_replacement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("renew_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("rebind_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("match_client_id", models.BooleanField(blank=True, null=True)),
                ("authoritative", models.BooleanField(blank=True, null=True)),
                ("reservations_global", models.BooleanField(blank=True, null=True)),
                (
                    "reservations_out_of_pool",
                    models.BooleanField(blank=True, null=True),
                ),
                ("reservations_in_subnet", models.BooleanField(blank=True, null=True)),
                ("calculate_tee_times", models.BooleanField(blank=True, null=True)),
                (
                    "t1_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "t2_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "cache_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("cache_max_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "adaptive_lease_time_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("store_extended_info", models.BooleanField(blank=True, null=True)),
                ("allocator", models.CharField(blank=True, null=True)),
                ("pd_allocator", models.CharField(blank=True, null=True)),
                ("relay", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "interface_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rapid_commit", models.BooleanField(blank=True, null=True)),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "client_class_definitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="definition_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evaluate_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_dhcp_shared_networks",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "require_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="require_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "child_subnets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Network",
                "verbose_name_plural": "Shared Networks",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DHCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("next_server", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "server_hostname",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "boot_file_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_valid_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_preferred_lifetime",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offer_lifetime", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_send_updates", models.BooleanField(blank=True, null=True)),
                ("ddns_override_no_update", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_override_client_update",
                    models.BooleanField(blank=True, null=True),
                ),
                ("ddns_replace_client_name", models.CharField(blank=True, null=True)),
                ("ddns_generated_prefix", models.CharField(blank=True, null=True)),
                ("ddns_qualifying_suffix", models.CharField(blank=True, null=True)),
                ("ddns_update_on_renew", models.BooleanField(blank=True, null=True)),
                (
                    "ddns_conflict_resolution_mode",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "ddns_ttl_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ddns_ttl", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_min", models.PositiveIntegerField(blank=True, null=True)),
                ("ddns_ttl_max", models.PositiveIntegerField(blank=True, null=True)),
                ("hostname_char_set", models.CharField(blank=True, max_length=255)),
                (
                    "hostname_char_replacement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("renew_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("rebind_timer", models.PositiveIntegerField(blank=True, null=True)),
                ("match_client_id", models.BooleanField(blank=True, null=True)),
                ("authoritative", models.BooleanField(blank=True, null=True)),
                ("reservations_global", models.BooleanField(blank=True, null=True)),
                (
                    "reservations_out_of_pool",
                    models.BooleanField(blank=True, null=True),
                ),
                ("reservations_in_subnet", models.BooleanField(blank=True, null=True)),
                ("calculate_tee_times", models.BooleanField(blank=True, null=True)),
                (
                    "t1_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "t2_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "cache_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("cache_max_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "adaptive_lease_time_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("store_extended_info", models.BooleanField(blank=True, null=True)),
                ("allocator", models.CharField(blank=True, null=True)),
                ("pd_allocator", models.CharField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(blank=True, default="active", max_length=50),
                ),
                (
                    "decline_probation_period",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "host_reservation_identifiers",
                    netbox_dhcp.fields.choice_array.ChoiceArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("echo_client_id", models.BooleanField(blank=True, null=True)),
                (
                    "relay_supplied_options",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(0),
                                django.core.validators.MaxValueValidator(255),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("server_id", models.CharField(blank=True, null=True)),
                (
                    "child_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_dhcp_dhcp_servers",
                        to="dcim.device",
                    ),
                ),
                (
                    "dhcp_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dhcp_servers",
                        to="netbox_dhcp.dhcpcluster",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "virtual_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_dhcp_dhcp_servers",
                        to="virtualization.virtualmachine",
                    ),
                ),
                (
                    "child_host_reservations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.hostreservation",
                    ),
                ),
                (
                    "child_shared_networks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.sharednetwork",
                    ),
                ),
                (
                    "child_subnets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_%(class)ss",
                        to="netbox_dhcp.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Server",
                "verbose_name_plural": "DHCP Servers",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="optiondefinition",
            constraint=models.UniqueConstraint(
                fields=("space", "code"), name="space_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="optiondefinition",
            constraint=models.UniqueConstraint(
                fields=("space", "name"), name="space_name_unique"
            ),
        ),
    ]
