# Generated by Django 5.2.5 on 2025-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiondefinition",
            name="family",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
