# Generated by Django 5.2.5 on 2025-09-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0215_rackreservation_status"),
        ("netbox_dhcp", "0001_initial"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpcluster",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=50),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_dhcp_servers",
                to="dcim.device",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="dhcp_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dhcp_servers",
                to="netbox_dhcp.dhcpcluster",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=50),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="virtual_machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_dhcp_servers",
                to="virtualization.virtualmachine",
            ),
        ),
    ]
