# Generated by Django 5.2.5 on 2025-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0002_dhcpcluster_status_dhcpserver_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclass",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="max_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="max_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="min_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="min_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="next_server",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="only_if_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="test",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="user_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
