# Generated by Django 5.2.7 on 2025-10-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0002_import_option_definitions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="always_send",
        ),
        migrations.RemoveField(
            model_name="option",
            name="never_send",
        ),
        migrations.AddField(
            model_name="option",
            name="send_option",
            field=models.CharField(blank=True, null=True),
        ),
    ]
