# Generated by Django 5.2.7 on 2025-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0003_remove_option_always_send_remove_option_never_send_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhcpserver",
            name="child_client_classes",
        ),
        migrations.RemoveField(
            model_name="hostreservation",
            name="assign_client_classes",
        ),
        migrations.RemoveField(
            model_name="option",
            name="assign_client_classes",
        ),
        migrations.RemoveField(
            model_name="pdpool",
            name="client_class",
        ),
        migrations.RemoveField(
            model_name="pdpool",
            name="client_class_definitions",
        ),
        migrations.RemoveField(
            model_name="pdpool",
            name="require_client_classes",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="client_class",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="client_class_definitions",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="require_client_classes",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="client_class",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="client_class_definitions",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="require_client_classes",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="client_class",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="client_class_definitions",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="require_client_classes",
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
    ]
