# Generated by Django 5.2.5 on 2025-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0003_clientclass_boot_file_name_clientclass_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclass",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
