# Generated by Django 5.2.5 on 2025-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0004_alter_clientclass_user_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclass",
            name="offer_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="only_in_additional_list",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="template_test",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
