# Generated by Django 5.2.7 on 2025-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0004_remove_dhcpserver_child_client_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhcpserver",
            name="child_host_reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)s_set",
                to="netbox_dhcp.hostreservation",
            ),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="child_shared_networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)s_set",
                to="netbox_dhcp.sharednetwork",
            ),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)s_set", to="netbox_dhcp.subnet"
            ),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)s_set",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)s_set",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)s_set", to="netbox_dhcp.subnet"
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)s_set",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="child_host_reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)s_set",
                to="netbox_dhcp.hostreservation",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="child_pd_pools",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)s_set", to="netbox_dhcp.pdpool"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="child_pools",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)s_set", to="netbox_dhcp.pool"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)s_set", to="netbox_dhcp.subnet"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_set", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)s_set",
                to="netbox_dhcp.clientclass",
            ),
        ),
    ]
