# Generated by Django 5.2.5 on 2025-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0004_alter_clientclass_only_if_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, default=""),
        ),
    ]
