# Generated by Django 5.2.5 on 2025-09-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0215_rackreservation_status"),
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0005_clientclass_offer_lifetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostreservation",
            name="circuit_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="host_reservations",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="duid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="flex_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="hw_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_host_reservations",
                to="dcim.macaddress",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="ip_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_host_reservations",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
