# Generated by Django 5.2.7 on 2025-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0005_alter_dhcpserver_child_host_reservations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientclass",
            name="only_if_required",
        ),
    ]
