# Generated by Django 5.2.5 on 2025-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0006_alter_dhcpserver_ddns_generated_prefix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optiondefinition",
            name="array",
            field=models.BooleanField(null=True),
        ),
    ]
