# Generated by Django 5.2.5 on 2025-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0006_hostreservation_circuit_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostreservation",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="excluded_prefixes",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_excluded_host_reservations", to="ipam.prefix"
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="ip_addresses",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_host_reservations", to="ipam.ipaddress"
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="next_server",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="offer_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="prefixes",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_host_reservations", to="ipam.prefix"
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
