# Generated by Django 5.2.7 on 2025-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0215_rackreservation_status"),
        ("netbox_dhcp", "0006_remove_clientclass_only_if_required"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserver",
            name="device_interfaces",
            field=models.ManyToManyField(
                blank=True, related_name="netbox_dhcp_dhcp_servers", to="dcim.interface"
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="virtual_machine_interfaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="netbox_dhcp_dhcp_servers",
                to="virtualization.vminterface",
            ),
        ),
    ]
