# Generated by Django 5.2.5 on 2025-09-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0007_remove_hostreservation_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostreservation",
            name="offer_lifetime",
        ),
    ]
