# Generated by Django 5.2.7 on 2025-10-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0007_dhcpserver_device_interfaces_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subnet",
            name="child_subnets",
        ),
    ]
