# Generated by Django 5.2.6 on 2025-09-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0007_alter_optiondefinition_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="options",
                to="netbox_dhcp.optiondefinition",
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="excluded_prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_pd_excluded_pools",
                to="ipam.prefix",
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_pd_pools",
                to="ipam.prefix",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ip_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_pools",
                to="ipam.iprange",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_subnets",
                to="ipam.prefix",
            ),
        ),
    ]
