# Generated by Django 5.2.6 on 2025-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0008_alter_option_definition_alter_pdpool_excluded_prefix_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclass",
            name="only_if_required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="only_in_additional_list",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="authoritative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="calculate_tee_times",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_override_client_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_override_no_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_send_updates",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="ddns_update_on_renew",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="echo_client_id",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="match_client_id",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="reservations_global",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="reservations_in_subnet",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="reservations_out_of_pool",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="store_extended_info",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="optiondefinition",
            name="array",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_override_client_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_override_no_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_send_updates",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_update_on_renew",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="authoritative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="calculate_tee_times",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_override_client_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_override_no_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_send_updates",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_update_on_renew",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="match_client_id",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="rapid_commit",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="reservations_global",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="reservations_in_subnet",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="reservations_out_of_pool",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="store_extended_info",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="authoritative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="calculate_tee_times",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_override_client_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_override_no_update",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_send_updates",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_update_on_renew",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="match_client_id",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="rapid_commit",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="reservations_global",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="reservations_in_subnet",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="reservations_out_of_pool",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="store_extended_info",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
