# Generated by Django 5.2.7 on 2025-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0008_remove_subnet_child_subnets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclass",
            name="template_test",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="test",
            field=models.TextField(blank=True),
        ),
    ]
