# Generated by Django 5.2.5 on 2025-09-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0008_remove_hostreservation_offer_lifetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostreservation",
            name="excluded_prefixes",
        ),
        migrations.RemoveField(
            model_name="hostreservation",
            name="ip_addresses",
        ),
        migrations.RemoveField(
            model_name="hostreservation",
            name="prefixes",
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="excluded_ipv6_prefixes",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_excluded_ipv6_host_reservations",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="ipv4_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_ipv4_host_reservations",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="ipv6_addresses",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_ipv6_host_reservations", to="ipam.ipaddress"
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="ipv6_prefixes",
            field=models.ManyToManyField(
                related_name="netbox_dhcp_ipv6_host_reservations", to="ipam.prefix"
            ),
        ),
    ]
