# Generated by Django 5.2.5 on 2025-09-15 13:44

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0009_remove_hostreservation_excluded_prefixes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "name",
                    models.CharField(
                        db_collation="natural_sort", max_length=255, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pool",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "ip_range",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_dhcp_pool",
                        to="ipam.iprange",
                    ),
                ),
                (
                    "require_client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="require_pools",
                        to="netbox_dhcp.clientclass",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Address Pool",
                "verbose_name_plural": "Address Pools",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
