# Generated by Django 5.2.6 on 2025-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0009_alter_clientclass_only_if_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostreservation",
            name="circuit_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="duid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="flex_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="hostname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
