# Generated by Django 5.2.7 on 2025-10-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0009_alter_clientclass_template_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientclass",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="clientclass",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="hostreservation",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="hostreservation",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="pdpool",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="pdpool",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="user_context",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="user_context",
        ),
    ]
