# Generated by Django 5.2.7 on 2025-10-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0010_remove_clientclass_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subnet",
            name="child_pd_pools",
        ),
        migrations.AddField(
            model_name="pdpool",
            name="subnet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_pd_pools",
                to="netbox_dhcp.subnet",
            ),
        ),
    ]
