# Generated by Django 5.2.5 on 2025-09-15 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0010_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdpool",
            name="client_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="delegated_length",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(128),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="excluded_prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netbox_dhcp_pd_excluded_pool",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_pd_pool",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="require_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="require_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pool",
            name="client_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ip_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_pool",
                to="ipam.iprange",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="require_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="require_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
    ]
