# Generated by Django 5.2.6 on 2025-10-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0011_alter_clientclass_boot_file_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": (
                    "definition__space",
                    "definition__code",
                    "definition__name",
                )
            },
        ),
    ]
