# Generated by Django 5.2.7 on 2025-10-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0011_remove_subnet_child_pd_pools_pdpool_subnet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhcpserver",
            name="child_shared_networks",
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="dhcp_server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_shared_networks",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
    ]
