# Generated by Django 5.2.5 on 2025-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0011_pdpool_client_class_pdpool_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdpool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="pool_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="evaluate_additional_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluate_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="pool_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="next_server",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="ddns",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dhcpcluster",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="client_classes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="netbox_dhcp.clientclass"
            ),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="next_server",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="option",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pool",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
