# Generated by Django 5.2.7 on 2025-10-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0012_remove_dhcpserver_child_shared_networks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subnet",
            name="child_pools",
        ),
        migrations.AddField(
            model_name="pool",
            name="subnet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_pools",
                to="netbox_dhcp.subnet",
            ),
        ),
    ]
