# Generated by Django 5.2.6 on 2025-09-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0012_pdpool_client_classes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            "HostReservation", "client_classes", "client_class_definitions"
        ),
        migrations.RenameField("PDPool", "client_classes", "client_class_definitions"),
        migrations.RenameField("Pool", "client_classes", "client_class_definitions"),
    ]
