# Generated by Django 5.2.6 on 2025-09-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0013_rename_client_classes_field"),
    ]

    operations = [
        migrations.RenameField(
            "HostReservation", "client_class_definitions", "assign_client_classes"
        ),
    ]
