# Generated by Django 5.2.6 on 2025-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        ("netbox_dhcp", "0013_alter_option_assigned_object_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="optiondefinition",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="optiondefinition",
            constraint=models.UniqueConstraint(
                fields=("space", "code"), name="space_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="optiondefinition",
            constraint=models.UniqueConstraint(
                fields=("space", "name"), name="space_name_unique"
            ),
        ),
    ]
