# Generated by Django 5.2.7 on 2025-11-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        ("ipam", "0083_vlangroup_populate_total_vlan_ids"),
        ("netbox_dhcp", "0013_remove_subnet_child_pools_pool_subnet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhcpserver",
            name="child_subnets",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="child_subnets",
        ),
        migrations.AddField(
            model_name="subnet",
            name="dhcp_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_subnets",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="shared_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_subnets",
                to="netbox_dhcp.sharednetwork",
            ),
        ),
        migrations.AddConstraint(
            model_name="subnet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("dhcp_server__isnull", False),
                            ("shared_network__isnull", True),
                        ),
                        models.Q(
                            ("dhcp_server__isnull", True),
                            ("shared_network__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="unique_parent_object",
                violation_error_message="Either DHCP Server or Shared Network is required, not both",
            ),
        ),
    ]
