# Generated by Django 5.2.6 on 2025-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0014_alter_optiondefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="data",
            field=models.CharField(blank=True),
        ),
    ]
