# Generated by Django 5.2.6 on 2025-09-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0014_rename_client_class_definitions_field"),
    ]

    operations = [
        migrations.RenameField(
            "PDPool", "require_client_classes", "required_client_classes"
        ),
    ]
