# Generated by Django 5.2.7 on 2025-11-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0215_rackreservation_status"),
        ("extras", "0133_make_cf_minmax_decimal"),
        ("ipam", "0083_vlangroup_populate_total_vlan_ids"),
        ("netbox_dhcp", "0014_remove_dhcpserver_child_subnets_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subnet",
            name="unique_parent_object",
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="child_host_reservations",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="child_host_reservations",
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="dhcp_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_host_reservations",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_host_reservations",
                to="netbox_dhcp.subnet",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("dhcp_server__isnull", False), ("subnet__isnull", True)
                        ),
                        models.Q(
                            ("dhcp_server__isnull", True), ("subnet__isnull", False)
                        ),
                        _connector="OR",
                    )
                ),
                name="host_reservation_unique_parent_object",
                violation_error_message="Either DHCP Server or Subnet is required, not both",
            ),
        ),
        migrations.AddConstraint(
            model_name="subnet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("dhcp_server__isnull", False),
                            ("shared_network__isnull", True),
                        ),
                        models.Q(
                            ("dhcp_server__isnull", True),
                            ("shared_network__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="subnet_unique_parent_object",
                violation_error_message="Either DHCP Server or Shared Network is required, not both",
            ),
        ),
    ]
