# Generated by Django 5.2.7 on 2025-11-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0015_remove_subnet_unique_parent_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": (
                    "definition__space",
                    "definition__code",
                    "definition__name",
                    "weight",
                )
            },
        ),
    ]
