# Generated by Django 5.2.6 on 2025-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0015_alter_option_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostreservation",
            name="assign_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="assign_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="assign_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="assign_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="client_class_definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="definition_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="client_class_definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="definition_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="client_class_definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="definition_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="client_class_definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="definition_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
    ]
