# Generated by Django 5.2.6 on 2025-10-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_dhcp", "0016_alter_hostreservation_assign_client_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="assigned_object_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="option",
            name="assigned_object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
