# Generated by Django 5.2.8 on 2025-11-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0016_option_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiondefinition",
            name="client_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_definitions",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="optiondefinition",
            name="dhcp_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_definitions",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="optiondefinition",
            name="space_code_unique",
        ),
        migrations.RemoveConstraint(
            model_name="optiondefinition",
            name="space_name_unique",
        ),
    ]
