# Generated by Django 5.2.5 on 2025-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0016_remove_pool_require_client_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subnet",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subnet",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
