# Generated by Django 5.2.8 on 2025-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0017_optiondefinition_client_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientclass",
            options={"ordering": ("-weight", "name")},
        ),
        migrations.AlterModelOptions(
            name="pdpool",
            options={"ordering": ("-weight", "name")},
        ),
        migrations.AlterModelOptions(
            name="pool",
            options={"ordering": ("-weight", "name")},
        ),
        migrations.AlterModelOptions(
            name="sharednetwork",
            options={"ordering": ("-weight", "name")},
        ),
        migrations.AlterModelOptions(
            name="subnet",
            options={"ordering": ("-weight", "name")},
        ),
        migrations.AddField(
            model_name="clientclass",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="pool",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="subnet",
            name="weight",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
