# Generated by Django 5.2.5 on 2025-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0017_sharednetwork_comment_sharednetwork_user_context_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="max_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="max_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="min_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="min_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="offer_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="max_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="max_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="min_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="min_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="offer_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
