# Generated by Django 5.2.8 on 2025-12-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0018_alter_clientclass_options_alter_pdpool_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhcpserver",
            name="client_classes",
        ),
        migrations.AddField(
            model_name="clientclass",
            name="dhcp_server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_class_definition_set",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
    ]
