# Generated by Django 5.2.5 on 2025-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0018_sharednetwork_max_preferred_lifetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="next_server",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="subnet",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="subnet",
            name="next_server",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="subnet",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
