# Generated by Django 5.2.5 on 2025-09-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0082_add_prefix_network_containment_indexes"),
        ("netbox_dhcp", "0019_sharednetwork_boot_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="prefix",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_shared_networks",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="prefix",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="netbox_dhcp_pools",
                to="ipam.prefix",
            ),
        ),
    ]
