# Generated by Django 5.2.8 on 2025-12-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        ("ipam", "0083_vlangroup_populate_total_vlan_ids"),
        ("netbox_dhcp", "0019_remove_dhcpserver_client_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="subnet_id",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="subnet",
            constraint=models.UniqueConstraint(
                fields=("subnet_id",), name="subnet_unique_subnet_id"
            ),
        ),
    ]
