# Generated by Django 5.2.5 on 2025-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0020_sharednetwork_prefix_subnet_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="ddns_conflict_resolution_mode",
            field=models.CharField(default="check-with-dhcid"),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_override_client_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_override_no_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_replace_client_name",
            field=models.CharField(default="never"),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_send_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_ttl",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="ddns_update_on_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="enable_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="hostname_char_replacement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pool",
            name="hostname_char_set",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_conflict_resolution_mode",
            field=models.CharField(default="check-with-dhcid"),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_override_client_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_override_no_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_replace_client_name",
            field=models.CharField(default="never"),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_send_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_ttl",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="ddns_update_on_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="enable_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="hostname_char_replacement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="hostname_char_set",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_conflict_resolution_mode",
            field=models.CharField(default="check-with-dhcid"),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_override_client_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_override_no_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_replace_client_name",
            field=models.CharField(default="never"),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_send_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_ttl",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="ddns_update_on_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="enable_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="hostname_char_replacement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subnet",
            name="hostname_char_set",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
