# Generated by Django 5.2.8 on 2025-12-06 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0216_latitude_longitude_validators"),
        ("netbox_dhcp", "0020_alter_subnet_subnet_id_and_more"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="DHCPServerInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "device_interfaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netbox_dhcp_dhcp_server_interfaces",
                        to="dcim.interface",
                    ),
                ),
                (
                    "virtual_machine_interfaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netbox_dhcp_dhcp_server_interfaces",
                        to="virtualization.vminterface",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="interfaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="dhcp_servers",
                to="netbox_dhcp.dhcpserverinterface",
            ),
        ),
    ]
