# Generated by Django 5.2.5 on 2025-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0021_pool_ddns_conflict_resolution_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pool",
            name="enable_updates",
        ),
        migrations.RemoveField(
            model_name="sharednetwork",
            name="enable_updates",
        ),
        migrations.RemoveField(
            model_name="subnet",
            name="enable_updates",
        ),
    ]
