# Generated by Django 5.2.8 on 2025-12-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0021_dhcpserverinterface_dhcpserver_interfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserverinterface",
            name="dhcp_server",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="netbox_dhcp.dhcpserver",
            ),
        ),
    ]
