# Generated by Django 5.2.5 on 2025-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0022_remove_pool_enable_updates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
