# Generated by Django 5.2.5 on 2025-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0022_remove_pool_enable_updates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="adaptive_lease_time_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="authoritative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="cache_max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="cache_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="calculate_tee_times",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="match_client_id",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="pd_allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="reservations_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="reservations_in_subnet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="reservations_out_of_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="store_extended_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pool",
            name="t1_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="t2_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="adaptive_lease_time_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="authoritative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="cache_max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="cache_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="calculate_tee_times",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="match_client_id",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="pd_allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="reservations_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="reservations_in_subnet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="reservations_out_of_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="store_extended_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="t1_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="t2_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="adaptive_lease_time_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="authoritative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="cache_max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="cache_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="calculate_tee_times",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="match_client_id",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="pd_allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="reservations_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="reservations_in_subnet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="reservations_out_of_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="store_extended_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="t1_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="t2_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
