# Generated by Django 5.2.8 on 2025-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0022_dhcpserverinterface_dhcp_server"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dhcpserverinterface",
            old_name="device_interfaces",
            new_name="device_interface",
        ),
        migrations.RenameField(
            model_name="dhcpserverinterface",
            old_name="virtual_machine_interfaces",
            new_name="virtual_machine_interface",
        ),
    ]
