# Generated by Django 5.2.8 on 2025-12-07 08:39

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        (
            "netbox_dhcp",
            "0023_rename_device_interfaces_dhcpserverinterface_device_interface_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserverinterface",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserverinterface",
            name="custom_field_data",
            field=models.JSONField(
                blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="dhcpserverinterface",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserverinterface",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
    ]
