# Generated by Django 5.2.5 on 2025-09-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0023_pool_adaptive_lease_time_threshold_pool_allocator_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pool",
            name="adaptive_lease_time_threshold",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="allocator",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="authoritative",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="cache_max_age",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="cache_threshold",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="calculate_tee_times",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="match_client_id",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="pd_allocator",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="rebind_timer",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="renew_timer",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="reservations_global",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="reservations_in_subnet",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="reservations_out_of_pool",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="store_extended_info",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="t1_percent",
        ),
        migrations.RemoveField(
            model_name="pool",
            name="t2_percent",
        ),
    ]
