# Generated by Django 5.2.8 on 2025-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0024_dhcpserverinterface_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="server_interfaces",
            field=models.ManyToManyField(
                blank=True, to="netbox_dhcp.dhcpserverinterface"
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="server_interfaces",
            field=models.ManyToManyField(
                blank=True, to="netbox_dhcp.dhcpserverinterface"
            ),
        ),
    ]
