# Generated by Django 5.2.5 on 2025-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0024_remove_pool_adaptive_lease_time_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="ddns_ttl_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="ddns_ttl_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="ddns_ttl_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
    ]
