# Generated by Django 5.2.6 on 2025-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0025_alter_pool_ddns_ttl_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="interface_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="rapid_commit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="relay",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="interface_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="rapid_commit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subnet",
            name="relay",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="subnet_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
