# Generated by Django 5.2.8 on 2025-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0025_sharednetwork_server_interfaces_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dhcpserverinterface",
            options={"ordering": ("id",)},
        ),
    ]
