# Generated by Django 5.2.6 on 2025-09-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0026_sharednetwork_interface_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednetwork",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)ss", to="netbox_dhcp.subnet"
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="child_host_reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)ss",
                to="netbox_dhcp.hostreservation",
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="child_pd_pools",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)ss", to="netbox_dhcp.pdpool"
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="child_pools",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)ss", to="netbox_dhcp.pool"
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)ss", to="netbox_dhcp.subnet"
            ),
        ),
    ]
