# Generated by Django 5.2.8 on 2025-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0216_latitude_longitude_validators"),
        ("extras", "0133_make_cf_minmax_decimal"),
        ("netbox_dhcp", "0027_alter_dhcpserverinterface_options_and_more"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dhcpserverinterface",
            name="dhcp_server_interface_device_vm",
        ),
        migrations.AddConstraint(
            model_name="dhcpserverinterface",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("device_interface__isnull", False),
                            ("virtual_machine_interface__isnull", True),
                        ),
                        models.Q(
                            ("device_interface__isnull", True),
                            ("virtual_machine_interface__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="dhcp_server_interface_device_vm",
                violation_error_message="Interface must refer to either a device or vm interface",
            ),
        ),
    ]
