# Generated by Django 5.2.6 on 2025-09-22 09:15

import django.contrib.postgres.fields
import django.core.validators
import netbox_dhcp.fields.choice_array
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0027_sharednetwork_subnets_subnet_host_reservations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserver",
            name="adaptive_lease_time_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="authoritative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="boot_file_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="cache_max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="cache_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="calculate_tee_times",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="child_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)ss",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="child_host_reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)ss",
                to="netbox_dhcp.hostreservation",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="child_shared_networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_%(class)ss",
                to="netbox_dhcp.sharednetwork",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="child_subnets",
            field=models.ManyToManyField(
                blank=True, related_name="parent_%(class)ss", to="netbox_dhcp.subnet"
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_conflict_resolution_mode",
            field=models.CharField(default="check-with-dhcid"),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_generated_prefix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_override_client_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_override_no_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_qualifying_suffix",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_replace_client_name",
            field=models.CharField(default="never"),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_send_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_ttl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_ttl_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_ttl_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_ttl_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_update_on_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="decline_probation_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="echo_client_id",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="host_reservation_identifiers",
            field=netbox_dhcp.fields.choice_array.ChoiceArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="hostname_char_replacement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="hostname_char_set",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="match_client_id",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="max_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="max_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="min_preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="min_valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="next_server",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="offer_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="pd_allocator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="preferred_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="relay_supplied_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(255),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="reservations_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="reservations_in_subnet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="reservations_out_of_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="server_hostname",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="server_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="store_extended_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="t1_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="t2_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="user_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
