# Generated by Django 5.2.8 on 2025-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0028_remove_dhcpserverinterface_dhcp_server_interface_device_vm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserver",
            name="ddns_enable_updates",
            field=models.BooleanField(default=False),
        ),
    ]
