# Generated by Django 5.2.8 on 2025-12-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp",
            "0028_remove_dhcpserverinterface_dhcp_server_interface_device_vm_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DDNS",
        ),
    ]
