# Generated by Django 5.2.6 on 2025-09-23 10:31

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_dhcp.fields.choice_array
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0133_make_cf_minmax_decimal"),
        ("netbox_dhcp", "0028_dhcpserver_adaptive_lease_time_threshold_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={},
        ),
        migrations.RemoveField(
            model_name="option",
            name="name",
        ),
        migrations.AddField(
            model_name="option",
            name="always_send",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="assign_client_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="assign_%(class)s",
                to="netbox_dhcp.clientclass",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="csv_format",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="data",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="never_send",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="OptionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("space", models.CharField(default="dhcpv4")),
                (
                    "code",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                ("type", models.CharField()),
                (
                    "record_types",
                    netbox_dhcp.fields.choice_array.ChoiceArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                ("encapsulate", models.CharField(blank=True, null=True)),
                ("array", models.BooleanField(default=False)),
                ("standard", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Definition",
                "verbose_name_plural": "Option Definitions",
                "ordering": ("space", "code", "name"),
                "unique_together": {("space", "code")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="option",
            name="definition",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="netbox_dhcp.optiondefinition",
            ),
        ),
    ]
