# Generated by Django 5.2.6 on 2025-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0029_alter_option_options_remove_option_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiondefinition",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
