# Generated by Django 5.2.9 on 2026-01-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp", "0029_delete_ddns"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclass",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="dhcpcluster",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dhcpcluster",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hostreservation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="option",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="optiondefinition",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="optiondefinition",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pdpool",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sharednetwork",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="clientclass",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="dhcpcluster",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="dhcpserver",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="hostreservation",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="option",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="optiondefinition",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pdpool",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pool",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="sharednetwork",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
