# Generated by Django 5.2.6 on 2025-09-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_dhcp", "0031_import_option_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="assigned_object_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="assigned_object_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
