from django import forms
from django.utils.translation import gettext_lazy as _

from netbox.forms import (
    NetBoxModelBulkEditForm,
    NetBoxModelFilterSetForm,
    NetBoxModelImportForm,
    NetBoxModelForm,
)
from utilities.forms.fields import TagFilterField
from utilities.forms.rendering import FieldSet
from utilities.forms import add_blank_choice
from ipam.choices import IPAddressFamilyChoices

from netbox_dhcp.models import Subnet
from .mixins import (
    NetBoxDHCPFilterFormMixin,
    NetBoxDHCPBulkEditFormMixin,
    CommonFilterFormMixin,
    CommonBulkEditFormMixin,
    ClientClassFormMixin,
    ClientClassFilterFormMixin,
    ClientClassImportFormMixin,
    ClientClassBulkEditFormMixin,
    LifetimeFilterFormMixin,
    LifetimeBulkEditFormMixin,
    BOOTPFilterFormMixin,
    BOOTPBulkEditFormMixin,
    PrefixFormMixin,
    PrefixFilterFormMixin,
    PrefixImportFormMixin,
    PrefixBulkEditFormMixin,
    DDNSUpdateFormMixin,
    DDNSUpdateFilterFormMixin,
    DDNSUpdateImportFormMixin,
    DDNSUpdateBulkEditFormMixin,
    LeaseFormMixin,
    LeaseFilterFormMixin,
    LeaseBulkEditFormMixin,
    NetworkFilterFormMixin,
    NetworkBulkEditFormMixin,
    ChildSubnetFormMixin,
    ChildSubnetFilterFormMixin,
    ChildSubnetImportFormMixin,
    ChildPoolFormMixin,
    ChildPoolFilterFormMixin,
    ChildPoolImportFormMixin,
    ChildPDPoolFormMixin,
    ChildPDPoolFilterFormMixin,
    ChildPDPoolImportFormMixin,
    ChildHostReservationFormMixin,
    ChildHostReservationFilterFormMixin,
    ChildHostReservationImportFormMixin,
)


__all__ = (
    "SubnetForm",
    "SubnetFilterForm",
    "SubnetImportForm",
    "SubnetBulkEditForm",
)


class SubnetForm(
    PrefixFormMixin,
    ClientClassFormMixin,
    DDNSUpdateFormMixin,
    LeaseFormMixin,
    ChildSubnetFormMixin,
    ChildPoolFormMixin,
    ChildPDPoolFormMixin,
    ChildHostReservationFormMixin,
    NetBoxModelForm,
):
    class Meta:
        model = Subnet

        fields = (
            "name",
            "description",
            "subnet_id",
            "prefix",
            "child_subnets",
            "child_pools",
            "child_pd_pools",
            "child_host_reservations",
            "next_server",
            "server_hostname",
            "boot_file_name",
            "client_class_definitions",
            "client_class",
            "require_client_classes",
            "evaluate_additional_classes",
            "offer_lifetime",
            "valid_lifetime",
            "min_valid_lifetime",
            "max_valid_lifetime",
            "preferred_lifetime",
            "min_preferred_lifetime",
            "max_preferred_lifetime",
            "renew_timer",
            "rebind_timer",
            "match_client_id",
            "authoritative",
            "reservations_global",
            "reservations_out_of_pool",
            "reservations_in_subnet",
            "calculate_tee_times",
            "t1_percent",
            "t2_percent",
            "cache_threshold",
            "cache_max_age",
            "adaptive_lease_time_threshold",
            "store_extended_info",
            "allocator",
            "pd_allocator",
            "rapid_commit",
            "hostname_char_set",
            "hostname_char_replacement",
            "ddns_send_updates",
            "ddns_override_no_update",
            "ddns_override_client_update",
            "ddns_replace_client_name",
            "ddns_generated_prefix",
            "ddns_qualifying_suffix",
            "ddns_update_on_renew",
            "ddns_conflict_resolution_mode",
            "ddns_ttl_percent",
            "ddns_ttl",
            "ddns_ttl_min",
            "ddns_ttl_max",
            "user_context",
            "comment",
            "tags",
        )

    fieldsets = (
        FieldSet(
            "name",
            "description",
            "subnet_id",
            "prefix",
            name=_("Subnet"),
        ),
        FieldSet(
            "child_subnets",
            "child_pools",
            "child_pd_pools",
            "child_host_reservations",
            name=_("Child Objects"),
        ),
        FieldSet(
            "client_class_definitions",
            name=_("Client Class Definitions"),
        ),
        FieldSet(
            "client_class",
            "require_client_classes",
            "relay",
            "interface_id",
            name=_("Selection"),
        ),
        FieldSet(
            "next_server",
            "server_hostname",
            "boot_file_name",
            name=_("BOOTP"),
        ),
        FieldSet(
            "offer_lifetime",
            "valid_lifetime",
            "min_valid_lifetime",
            "max_valid_lifetime",
            "preferred_lifetime",
            "min_preferred_lifetime",
            "max_preferred_lifetime",
            "evaluate_additional_classes",
            "user_context",
            "comment",
            name=_("Assignment"),
        ),
        FieldSet(
            "renew_timer",
            "rebind_timer",
            "calculate_tee_times",
            "t1_percent",
            "t2_percent",
            "adaptive_lease_time_threshold",
            "match_client_id",
            "reservations_global",
            "reservations_out_of_pool",
            "reservations_in_subnet",
            "cache_threshold",
            "cache_max_age",
            "authoritative",
            "store_extended_info",
            "allocator",
            "pd_allocator",
            "rapid_commit",
            name=_("Lease"),
        ),
        FieldSet(
            "hostname_char_set",
            "hostname_char_replacement",
            "ddns_send_updates",
            "ddns_override_no_update",
            "ddns_override_client_update",
            "ddns_replace_client_name",
            "ddns_generated_prefix",
            "ddns_qualifying_suffix",
            "ddns_update_on_renew",
            "ddns_conflict_resolution_mode",
            "ddns_ttl_percent",
            "ddns_ttl",
            "ddns_ttl_min",
            "ddns_ttl_max",
            name=_("Dynamic DNS Update"),
        ),
        FieldSet(
            "tags",
            name=_("Tags"),
        ),
    )


class SubnetFilterForm(
    NetBoxDHCPFilterFormMixin,
    PrefixFilterFormMixin,
    BOOTPFilterFormMixin,
    ClientClassFilterFormMixin,
    LifetimeFilterFormMixin,
    CommonFilterFormMixin,
    DDNSUpdateFilterFormMixin,
    LeaseFilterFormMixin,
    NetworkFilterFormMixin,
    ChildSubnetFilterFormMixin,
    ChildPoolFilterFormMixin,
    ChildPDPoolFilterFormMixin,
    ChildHostReservationFilterFormMixin,
    NetBoxModelFilterSetForm,
):
    model = Subnet

    fieldsets = (
        FieldSet(
            "q",
            "filter_id",
            "tag",
        ),
        FieldSet(
            "name",
            "description",
            "family",
            "subnet_id",
            "prefix_id",
            name=_("Subnet"),
        ),
        FieldSet(
            "child_subnet_id",
            "child_pool_id",
            "child_pd_pool_id",
            "child_host_reservation_id",
            name=_("Child Objects"),
        ),
        FieldSet(
            "client_class_definition_id",
            name=_("Client Class Definitions"),
        ),
        FieldSet(
            "client_class_id",
            "required_client_class_id",
            "relay",
            "interface_id",
            name=_("Selection"),
        ),
        FieldSet(
            "next_server",
            "server_hostname",
            "boot_file_name",
            name=_("BOOTP"),
        ),
        FieldSet(
            "offer_lifetime",
            "valid_lifetime",
            "min_valid_lifetime",
            "max_valid_lifetime",
            "preferred_lifetime",
            "min_preferred_lifetime",
            "max_preferred_lifetime",
            "evaluate_additional_class_id",
            "comment",
            name=_("Assignment"),
        ),
        FieldSet(
            "renew_timer",
            "rebind_timer",
            "calculate_tee_times",
            "t1_percent",
            "t2_percent",
            "adaptive_lease_time_threshold",
            "match_client_id",
            "reservations_global",
            "reservations_out_of_pool",
            "reservations_in_subnet",
            "cache_threshold",
            "cache_max_age",
            "authoritative",
            "store_extended_info",
            "allocator",
            "pd_allocator",
            "rapid_commit",
            name=_("Lease"),
        ),
        FieldSet(
            "hostname_char_set",
            "hostname_char_replacement",
            "ddns_send_updates",
            "ddns_override_no_update",
            "ddns_override_client_update",
            "ddns_replace_client_name",
            "ddns_generated_prefix",
            "ddns_qualifying_suffix",
            "ddns_update_on_renew",
            "ddns_conflict_resolution_mode",
            "ddns_ttl_percent",
            "ddns_ttl",
            "ddns_ttl_min",
            "ddns_ttl_max",
            name=_("Dynamic DNS Update"),
        ),
    )

    family = forms.ChoiceField(
        choices=add_blank_choice(IPAddressFamilyChoices),
        required=False,
        label=_("Address Family"),
    )

    tag = TagFilterField(Subnet)


class SubnetImportForm(
    PrefixImportFormMixin,
    ClientClassImportFormMixin,
    DDNSUpdateImportFormMixin,
    ChildSubnetImportFormMixin,
    ChildPoolImportFormMixin,
    ChildPDPoolImportFormMixin,
    ChildHostReservationImportFormMixin,
    NetBoxModelImportForm,
):
    class Meta:
        model = Subnet

        fields = (
            "name",
            "description",
            "subnet_id",
            "prefix",
            "child_subnets",
            "child_pools",
            "child_pd_pools",
            "child_host_reservations",
            "next_server",
            "server_hostname",
            "boot_file_name",
            "client_class_definitions",
            "client_class",
            "require_client_classes",
            "evaluate_additional_classes",
            "offer_lifetime",
            "valid_lifetime",
            "min_valid_lifetime",
            "max_valid_lifetime",
            "preferred_lifetime",
            "min_preferred_lifetime",
            "max_preferred_lifetime",
            "relay",
            "interface_id",
            "rapid_commit",
            "hostname_char_set",
            "hostname_char_replacement",
            "ddns_send_updates",
            "ddns_override_no_update",
            "ddns_override_client_update",
            "ddns_replace_client_name",
            "ddns_generated_prefix",
            "ddns_qualifying_suffix",
            "ddns_update_on_renew",
            "ddns_conflict_resolution_mode",
            "ddns_ttl_percent",
            "ddns_ttl",
            "ddns_ttl_min",
            "ddns_ttl_max",
            "user_context",
            "comment",
            "tags",
        )


class SubnetBulkEditForm(
    NetBoxDHCPBulkEditFormMixin,
    PrefixBulkEditFormMixin,
    BOOTPBulkEditFormMixin,
    ClientClassBulkEditFormMixin,
    LifetimeBulkEditFormMixin,
    CommonBulkEditFormMixin,
    DDNSUpdateBulkEditFormMixin,
    LeaseBulkEditFormMixin,
    NetworkBulkEditFormMixin,
    NetBoxModelBulkEditForm,
):
    model = Subnet

    fieldsets = (
        FieldSet(
            "description",
            "prefix",
            name=_("Subnet"),
        ),
        FieldSet(
            "client_class_definitions",
            name=_("Client Class Definitions"),
        ),
        FieldSet(
            "client_class",
            "require_client_classes",
            "relay",
            "interface_id",
            name=_("Selection"),
        ),
        FieldSet(
            "next_server",
            "server_hostname",
            "boot_file_name",
            name=_("BOOTP"),
        ),
        FieldSet(
            "offer_lifetime",
            "valid_lifetime",
            "min_valid_lifetime",
            "max_valid_lifetime",
            "preferred_lifetime",
            "min_preferred_lifetime",
            "max_preferred_lifetime",
            "evaluate_additional_classes",
            "user_context",
            "comment",
            name=_("Assignment"),
        ),
        FieldSet(
            "renew_timer",
            "rebind_timer",
            "calculate_tee_times",
            "t1_percent",
            "t2_percent",
            "adaptive_lease_time_threshold",
            "match_client_id",
            "reservations_global",
            "reservations_out_of_pool",
            "reservations_in_subnet",
            "cache_threshold",
            "cache_max_age",
            "authoritative",
            "store_extended_info",
            "allocator",
            "pd_allocator",
            "rapid_commit",
            name=_("Lease"),
        ),
        FieldSet(
            "hostname_char_set",
            "hostname_char_replacement",
            "ddns_send_updates",
            "ddns_override_no_update",
            "ddns_override_client_update",
            "ddns_replace_client_name",
            "ddns_generated_prefix",
            "ddns_qualifying_suffix",
            "ddns_update_on_renew",
            "ddns_conflict_resolution_mode",
            "ddns_ttl_percent",
            "ddns_ttl",
            "ddns_ttl_min",
            "ddns_ttl_max",
            name=_("Dynamic DNS Update"),
        ),
    )

    nullable_fields = (
        "description",
        "next_server",
        "server_hostname",
        "boot_file_name",
        "client_class_definitions",
        "client_class",
        "require_client_classes",
        "evaluate_additional_classes",
        "offer_lifetime",
        "valid_lifetime",
        "min_valid_lifetime",
        "max_valid_lifetime",
        "preferred_lifetime",
        "min_preferred_lifetime",
        "max_preferred_lifetime",
        "renew_timer",
        "rebind_timer",
        "t1_percent",
        "t2_percent",
        "adaptive_lease_time_threshold",
        "cache_threshold",
        "cache_max_age",
        "relay",
        "interface_id",
        "rapid_commit",
        "hostname_char_set",
        "hostname_char_replacement",
        "ddns_generated_prefix",
        "ddns_qualifying_suffix",
        "ddns_ttl_percent",
        "ddns_ttl",
        "ddns_ttl_min",
        "ddns_ttl_max",
        "user_context",
        "comment",
    )
